# Jekyll main configuration file
# See https://jekyllrb.com/docs/configuration/ to further customize this file
# Defaults settings https://jekyllrb.com/docs/configuration/#default-configuration

title: Gabriella Radke's homepage

logo: /assets/img/profile.jpg

description: Applied mathematician on the way to become a computer engineer. Experience at the data team in a p2p lending fintech and at the middle office in the energy sector.

url: https://gabriellaradke.github.io/

theme: jekyll-theme-minimal

icon: 📖

google_site_verification: yNSm1-yXjwPAf4RBuY8-Z1UaYZTyHmMtkYh11AeFj5Y

google_analytics: G-P83K10G4SM
