# Jekyll main configuration file
# See https://jekyllrb.com/docs/configuration/ to further customize this file
# Defaults settings https://jekyllrb.com/docs/configuration/#default-configuration

title: gabriellaradke

url: https://gabriellaradke.github.io/

theme: jekyll-theme-minimal

google_site_verification: yNSm1-yXjwPAf4RBuY8-Z1UaYZTyHmMtkYh11AeFj5Y
