# Jekyll main configuration file
# See https://jekyllrb.com/docs/configuration/ to further customize this file
# Defaults settings https://jekyllrb.com/docs/configuration/#default-configuration

title: Gabriella Radke's homepage

logo: /assets/img/profile.jpg

description: Matemática aplicada aspirante a engenheira de computação. Experiência no time de dados de uma fintech de crédito p2p e na equipe de middle no setor energético.

url: https://gabriellaradke.github.io/

theme: jekyll-theme-minimal

icon: 📖

google_site_verification: yNSm1-yXjwPAf4RBuY8-Z1UaYZTyHmMtkYh11AeFj5Y

google_analytics: G-P83K10G4SM
